controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

check_jeux:
    path: /jeux/{id}/check
    defaults: { _controller: Jeux:check }
    options:
        expose: true

check_sons:
    path: /jeux/{jeuId}/son/{sonId}/check
    defaults: { _controller: Jeux:checkSons }
    options:
        expose: true

check_sons_reponse:
    path: /son/{sonId}/check/{jeuId}
    defaults: { _controller: Son:checkSonReponse }
    options:
        expose: true

check_reponse:
    path: /jeux/reponse/{id}/get
    defaults: { _controller: Jeux:getReponse }
    options:
        expose: true

check_difficulte:
    path: /jeux/difficulte/{difficulte}/get
    defaults: { _controller: Jeux:getQuestionsByDifficulty }
    options:
        expose: true

get_score:
    path: /jeux/score/{jeu}/get
    defaults: { _controller: Jeux:getScore }
    options:
        expose: true

set_score:
    path: /jeux/score/{jeu}/set
    defaults: { _controller: Jeux:setScore }
    options:
        expose: true

verouillage_theme:
    path: /theme/question/{id}/verouillage
    defaults: { _controller: Theme:verouillage }
    options:
        expose: true