controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"



my_route_to_expose:
    path: /jeux/{id}/check
    defaults: { _controller: Jeux:check }
    options:
        expose: true